### ISSUE TITLE
Non-printing character in some trees

### ISSUE THREAD

**Issue by LoicGrobol** [UniversalDependencies/UD_French-ParTUT#2]
[[U+00AD] SOFT HYPHEN](https://www.fileformat.info/info/unicode/char/00ad/index.htm) appears in the following trees

- fr_partut-ud-134: tokens 10 and 43
- fr_partut-ud-155: token 10
- fr_partut-ud-185: tokens 43 and 58
- fr_partut-ud-185: tokens 17 and 21
- fr_partut-ud-270: as part of token 20
- fr_partut-ud-357: tokens 3 and 

This character is meant to represent “an invisible format character indicating a possible hyphenation location”. In fr_partut-ud-270 it seems to a result of a wrong conversion of the minus character, I am less sure in other places.

Since this is a non-printing control character, it would see reasonable to exclude it from tokens and in particular to avoid having it as a single token. It can also cause issues with automatic processing since some tools [e.g Moses](https://github.com/moses-smt/mosesdecoder/blob/master/scripts/tokenizer/remove-non-printing-char.perl) remove non-printing characters, resulting in an empty token.

**Comment by nschneid** [comment]
The English policy is to keep such characters in the token form, though maybe there should be a feature in MISC that removes it. UniversalDependencies/UD_English-EWT#83

**Comment by dan-zeman** [comment]
I agree that they should not be erased if they were in the original text; but if they are actually typos (because it should have been HYPHEN-MINUS), then they should be annotated accordingly.

**Comment by LoicGrobol** [comment]
I had a look at the original files (both in the treebank and the europarl source) and they are present, but it looks like almost all of them should have been `—` instead (they are annotated as parenthetical too) or the one HYPHEN MINUS. So could we maybe use `—` instead, at least for those that stand as full words in the trees? I understand the idea of preserving the link to the source, but having words that are fully non-printing feels uncomfortable.

```text
************** Frase FRENCH_EUROPARL-77 ************** 
1 Les (LE ART DEF ALLVAL PL) [43;VERB-SUBJ]
2 événements (ÉVÉNEMENT NOUN COMMON M PL) [1;DET+DEF-ARG]
3 qui (QUI PRON RELAT ALLVAL ALLVAL LSUBJ+LIOBJ+OBL) [5;VERB-SUBJ]
4 se (SE PRON REFL-IMPERS ALLVAL ALLVAL 3 LSUBJ+LOBJ+OBL) [6;EMPTYCOMPL]
5 sont (ÊTRE VERB AUX IND PRES INTRANS 3 PL) [6;AUX+TENSE]
6 produits (PRODUIRE VERB MAIN PARTICIPLE PAST TRANS ALLVAL ALLVAL) [2;VERB-RMOD+RELCL]
7 la (LE ART DEF F SING) [5;NOUN-RMOD-TIME]
8 semaine (SEMAINE NOUN COMMON F SING) [7;DET+DEF-ARG]
9 dernière (DERNIER ADJ ORDIN F SING) [8;ADJC+ORDIN-RMOD]
10 ­ (#\­ SPECIAL) [2;OPEN+PARENTHETICAL]
11 qui (QUI PRON RELAT ALLVAL ALLVAL LSUBJ+LIOBJ+OBL) [13;VERB-SUBJ]
12 sont (ÊTRE VERB AUX IND PRES INTRANS 3 PL) [13;AUX+TENSE]
13 nés (NAÎTRE VERB MAIN PARTICIPLE PAST INTRANS PL M) [2;VERB-RMOD+RELCL]
14 en (EN PREP MONO) [13;PREP-RMOD]
15 marge (MARGE NOUN COMMON M SING) [14;PREP-ARG]
16 de (DE PREP MONO) [15;PREP-RMOD]
17 la (LE ART DEF F SING) [16;PREP-ARG]
18 Conférence (CONFÉRENCE NOUN COMMON F SING) [17;DET+DEF-ARG]
19 des (DE PREP MONO) [18;PREP-RMOD]
19.1 des (LE ART DEF ALLVAL PL) [19;PREP-ARG]
20 présidents (PRÉSIDENT NOUN COMMON M PL) [19.1;DET+DEF-ARG]
21 et (ET CONJ COORD COORD) [13;COORD+BASE]
22 se (SE PRON REFL-IMPERS ALLVAL ALLVAL 3 LSUBJ+LOBJ+OBL) [23;EMPTYCOMPL]
23 servent (SERVIR VERB MAIN IND PRES TRANS 3 PL) [21;COORD2ND+BASE]
23.10 t [11f] (QUI PRON RELAT ALLVAL ALLVAL LSUBJ+LIOBJ+OBL) [23;VERB-SUBJ]
24 d' (DE PREP MONO) [23;VERB-INDCOMPL-THEME]
25 elle (ELLE PRON PERS F SING 3 LSUBJ+LOBJ+OBL) [24;PREP-ARG]
26 dans (DANS PREP MONO) [23;PREP-RMOD]
27 le (LE ART DEF M SING) [26;PREP-ARG]
28 seul (SEUL ADJ QUALIF M SING) [29;ADJC+QUALIF-RMOD]
29 but (BUT NOUN COMMON M SING) [27;DET+DEF-ARG]
30 de (DE PREP MONO) [29;PREP-RMOD]
31 corroborer (CORROBORER VERB MAIN INFINITE PRES TRANS) [30;PREP-ARG]
31.10 t [23.10f] (QUI PRON RELAT ALLVAL ALLVAL LSUBJ+LIOBJ+OBL) [31;VERB-SUBJ]
32 et (ET CONJ COORD COORD) [30;COORD+BASE]
33 de (DE PREP MONO) [32;COORD2ND+BASE]
34 ratifier (RATIFIER VERB MAIN INFINITE PRES TRANS) [33;PREP-ARG]
34.10 t [31.10f] (QUI PRON RELAT ALLVAL ALLVAL LSUBJ+LIOBJ+OBL) [34;VERB-SUBJ]
35 des (DES ART INDEF ALLVAL PL) [34;VERB-OBJ]
36 décisions (DÉCISION NOUN COMMON F PL DÉCIDER TRANS) [35;DET+INDEF-ARG]
37 prises (PRENDRE VERB MAIN PARTICIPLE PAST TRANS PL F) [36;VERB-RMOD+RELCL+REDUC]
37.10 t [36p] (DÉCISION NOUN COMMON F PL DÉCIDER TRANS) [37;VERB-OBJ/VERB-SUBJ]
37.11 t [] (GENERIC-T PRON PERS ALLVAL ALLVAL ALLVAL) [37;VERB-SUBJ/VERB-INDCOMPL-AGENT]
38 en (EN PREP MONO) [37;PREP-RMOD]
39 dehors (DEHORS ADV MANNER) [38;PREP-ARG]
40 de (DE PREP MONO) [37;CONTIN+PREP]
41 celle-ci (CELUI-CI PRON DEMONS F SING 3 LSUBJ+LOBJ+LIOBJ+OBL) [40;PREP-ARG]
42 ­ (#\­ SPECIAL) [2;CLOSE+PARENTHETICAL]
43 créent (CRÉER VERB MAIN IND PRES TRANS 3 PL) [0;TOP-VERB]
44 un (UN ART INDEF M SING) [43;VERB-OBJ]
45 dilemme (DILEMME NOUN COMMON M SING) [44;DET+INDEF-ARG]
46 : (#\: PUNCT) [43;END]
```

**Comment by bguil** [comment]
I've changed these cases (https://github.com/UniversalDependencies/UD_French-ParTUT/commit/50785cbea33d6702baeaf1dbb6b3336bb32904cc) according to https://universaldependencies.org/u/overview/typos.html.
I've fixed the lemmas, added `Typo=Yes` and `CorrectForm=-`.
